/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include<stdio.h>
#include<opencv2/opencv.hpp>
/* Header for class com_example_agnieszka_openvctest_OpencvNativeClass */
using namespace cv;
using namespace std;

#ifndef _Included_com_example_agnieszka_openvctest_OpencvNativeClass
#define _Included_com_example_agnieszka_openvctest_OpencvNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_agnieszka_openvctest_OpencvNativeClass
 * Method:    cannyDetect
 * Signature: (JJ)V
 */

void cannyDetect(Mat img, Mat& canny);

JNIEXPORT void JNICALL Java_com_example_agnieszka_openvctest_OpencvNativeClass_cannyDetect
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
